# golangci-lint configuration
# Compatible with golangci-lint v1.x (matches GitHub Actions)

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  go: '1.23'

linters:
  enable:
    - bodyclose
    - errcheck
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - depguard  # Too restrictive for this project
    - gosec     # Security issues need case-by-case review

linters-settings:
  govet:
    enable:
      - shadow
      - fieldalignment
  misspell:
    locale: US
  # revive: using default settings

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
