# golangci-lint configuration
# Compatible with golangci-lint v2.x
version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  go: '1.23'

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - misspell
    - unconvert
    - unparam
  disable:
    - depguard
    - gosec

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
