repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: go-fmt
        name: gofmt
        entry: gofmt
        language: system
        args: [-w]
        files: \.go$

      - id: go-imports
        name: goimports
        entry: goimports
        language: system
        args: [-w]
        files: \.go$

      - id: golangci-lint-check
        name: golangci-lint check (non-blocking)
        entry: bash -c 'golangci-lint run --timeout=5m --max-issues-per-linter=5 --max-same-issues=3 || true'
        language: system
        files: \.go$
        pass_filenames: false
