source 'https://rubygems.org'

gem 'jekyll', '~> 4.3'
gem 'jekyll-feed', '~> 0.15'
gem 'jekyll-sitemap', '~> 1.4'
gem 'jekyll-seo-tag', '~> 2.8'

group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-sitemap'
  gem 'jekyll-seo-tag'
end

# For GitHub Pages compatibility
gem 'github-pages', group: :jekyll_plugins
